name: Create Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from conf.yml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^[[:space:]]*version:[[:space:]]*//p' conf.yml | head -n 1)
          VERSION=${VERSION//\"/}
          VERSION=${VERSION//\'/}
          echo "Detected version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Blueprint Build
        id: blueprint_build
        uses: zephrynis/blueprint-export@v1.0.0

      - name: Push binary
        id: push_binary
        uses: actions/upload-artifact@v3
        with:
          name: monacobp.blueprint
          path: monacobp.blueprint
          retention-days: 10
